export SPARK_HOME=/usr/spark/spark-2.3.0-bin-hadoop2.7
export PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
export CLASSPATH=.:$CLASSPATH:$SPARK_HOME/jars
export SPARK_CLASSPATH=.:$CLASSPATH:$HADOOP_CLASSPATH:$HIVE_HOME/lib:$SPARK_HOME/jars
